### ISSUE TITLE
[NumberGuesser] try-catch

### ISSUE THREAD

**Issue by pavel-b-novikov** [gunsdontkillpeople/nsudotnet#2]
```
             try
            {
                _name = Console.ReadLine();
            }
            catch (Exception)
            {

            }
```

Скажите, в чем сакральный смысл этого кода?
А вот еще момент - у вас весь процесс проверки введенного числа обернут в try-catch. Выбрасывать и ловить исключения при парсеринге числа - слишком тяжело. Пожалуйста, найдите способ сократить кол-во исключений.

**Comment by gunsdontkillpeople** [comment]
Убрал try-catch, поменял на if-else и паршу теперь через Int32.TryParse(String, Int32)
