### ISSUE TITLE
[Rss2Email] Безграмотные .Dispose

### ISSUE THREAD

**Issue by pavel-b-novikov** [gunsdontkillpeople/nsudotnet#3]
Уберите эту мерзость, перепишите диспоз как нормальный человек.

**Comment by gunsdontkillpeople** [comment]
Обернул в using вместо этой мерзости

**Comment by pavel-b-novikov** [comment]
Не, не вижу

**Comment by gunsdontkillpeople** [comment]
У меня реально нет больше такой гадости(.Despose) в коде

**Comment by pavel-b-novikov** [comment]
теперь вижу
