### ISSUE TITLE
[Rss2Email] XmlNode

### ISSUE THREAD

**Issue by pavel-b-novikov** [gunsdontkillpeople/nsudotnet#4]
Я ценю что вы умеете читать XML из потока, но попробуйте, пожалуйста, через атрибуты XML-сериализации (гугл подскажет)

**Comment by gunsdontkillpeople** [comment]
Сделал

**Comment by pavel-b-novikov** [comment]
Ну вот же, вот! Удобнее?

**Comment by gunsdontkillpeople** [comment]
Удобнее конечно, но пришлось разбираться дольше чем с энигмой)

**Comment by pavel-b-novikov** [comment]
В этом блин и смысл, что вы один раз разобрались - и до конца жизни можете использовать удобный подход, а освободившееся время тратить на поедание еды, например. А если вы будете писать говнокод не разбираясь - вы будете тратить бешеные часы своей профессиональной жизни впустую.
